FROM docker.io/node:slim

WORKDIR /yepkitanalytics
COPY . .
RUN npm install

EXPOSE 5999
ENV PORT_SRV 0
ENV MESSAGE_REFERENCE 0
ENV MESSAGE_REFERENCE_DATE 0
ENV PLUGIN_NAME 0
ENV PLUGIN_VERSION 0
ENV SHIPPING_SYSTEM_PLATFORM_NAME 0
ENV SHIPPING_SYSTEM_PLATFORM_VERSION 0
ENV WEBSTORE_PLATFORM_NAME 0
ENV WEBSTORE_PLATFORM_VERSION 0
ENV AUTHORIZATION 0
ENV CLIENT_HOST 0
ENV CLIENT_PORT 0
ENV CLIENT_ID 0
ENV GROUP_ID 0
ENV TOPIC_CREATEORDER 0
ENV TOPIC_CREATEPICKUP 0

CMD [ "node", "src/index.js" ]

